### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/ndx-photometry#12]
I am raising this issue to discuss some general improvements to the photometry extension. For example,
- the photodetectors table has an attribute for peak wavelength, which I have previously used to specify the emission filter wavelength. However, it has come to my attention in the lerner conversion that the photodetector peak wavelength is not the same as the wavelength of the emission filter. To clear up this ambiguity, I propose that we add a fluorescence mini cube object which can store metadata information about the emission filter, dichroic mirror, and excitation filter (see [schematic](https://www.mightexbio.com/wp-content/uploads/2020/01/blogpost3_fig1_v2.jpg) by MightexBio).
- it may be useful for the fluorophores table to store the peak excitation wavelength and peak emission wavelength for each fluorophore.
- stereotactic coordinates for the fibers table
- DeconvolvedRoiResponseSeries --> DeconvolvedFiberPhotometryResponseSeries

**Comment by luiztauffer** [comment]
@pauladkisson with PR #14 we include the excitation and emisison lambdas for the fluorophores, which will solve the ambiguity you found.
Do you still see the need for a mini cube object? I feel like it might be unnecessary at this point.

**Comment by pauladkisson** [comment]
Yes, I still feel that we need an object to describe the set of optical filters typically contained in a minicube. Maybe we can call it `FiltersTable`, which would have entries for the emission filter, excitation filter, and dichroic mirror. The ambiguity that I pointed out earlier what is between the peak wavelength of the emission filter and the peak sensitivity wavelength of the photodetector itself. This ambiguity is still present even with excitation and emission wave lengths for the fluorophores.
